# basic
verbose 1
species homo_sapiens
format vcf
json 1

# reference/cache
offline 1
cache 1
dir_cache /opt/vep/cache

# performance
fork 1

# annotations
variant_class 1
symbol 1
protein 1
hgvs 1
hgvsg 1
merged 1
mane 1
flag_pick 1
sift b
polyphen b
regulatory 1
motif 1
distance 0
check_existing 1

# custom annotations
custom file=/opt/vep/custom_annotations/sscvdb/sscvdb.ver1.1.all.variant.vcf.gz,short_name=sscvdb,format=vcf,type=exact,fields=SJ_key%Motif_type%Predicted_splicing_type%Sample_count%Exon_number%Primary_SS_pos%Matching_SS_pos%Hijacked_SS_pos%Distance_from_hijacked_SS%SJ_location%MaxEntScore_Ref%MaxEntScore_Alt%MaxEntScore_Diff


# plugins
dir_plugins /opt/vep/plugins
plugin AlphaMissense,file=/opt/vep/plugins/cache/AlphaMissense/AlphaMissense_hg38.tsv.gz
plugin CADD,snv=/opt/vep/plugins/cache/CADD/v1.7/GRCh38/whole_genome_SNVs.tsv.gz,indels=/opt/vep/plugins/cache/CADD/v1.7/GRCh38/gnomad.genomes.r4.0.indel.tsv.gz,sv=/opt/vep/plugins/cache/CADD-SV/v1.1/prescored_variants.tsv.gz
plugin dbNSFP,/opt/vep-nf/vep_plugins/cache/dbNSFP/dbNSFP5.3a_grch38.gz,\
REVEL_score,ClinPred_score,ClinPred_pred,BayesDel_addAF_score,BayesDel_addAF_pred,PrimateAI_score,PrimateAI_pred,MPC_score,MetaRNN_score,MetaRNN_pred,GERP++_RS,phyloP100way_vertebrate,phastCons100way_vertebrate,gnomAD_lof.oe,gnomAD_mis.oe,gnomAD_LOEUF,gnomAD_MOEUF

# output behavior
force_overwrite 1
no_stats 1
