# basic
verbose 1
species homo_sapiens

# input
format vcf

# output
json 1

# reference
assembly GRCh37

# cache
offline 1
cache 1
dir_cache /opt/vep/cache
vep_version 115.0
cache_version 115

# performance
fork 0

# annotations
variant_class 1
symbol 1
protein 1
hgvs 1
hgvsg 1
merged 1
flag_pick 1
sift b
polyphen b
regulatory 1
distance 0
check_existing 1

# custom annotations

# plugins
dir_plugins /opt/vep/plugins
plugin CADD,snv=/opt/vep/plugins/cache/CADD/v1.7/GRCh37/whole_genome_SNVs.tsv.gz

# output behavior
force_overwrite 1
no_stats 1
